name: GPU - Run Integration Tests 2.0

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  pytorch-build-image-gpu:
    runs-on: [single-gpu, nvidia-gpu, t4, ci]
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerfiles/pytorch/gpu/Dockerfile
          tags: starlette-transformers:gpu
          outputs: type=oci,dest=/tmp/starlette-transformers-gpu.tar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Upload starlette-gpu image as artifact
        env:
          ACTIONS_STEP_DEBUG: true
        uses: actions/upload-artifact@v4
        with:
          name: starlette-transformers-gpu
          path: /tmp/starlette-transformers-gpu.tar
  pytorch-integration-test-gpu:
    needs: pytorch-build-image-gpu
    runs-on: [single-gpu, nvidia-gpu, t4, ci]
    env:
      AWS_REGION: us-east-1
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Download artifacts (Docker images) from previous workflows
        uses: actions/download-artifact@v3
        with:
          name: starlette-transformers-gpu
          path: /tmp/starlette-transformers-gpu.tar
      - run: |
          ls -all /tmp/starlette-transformers-gpu.tar
      - name: Load Docker images from previous workflows
        run: |
          docker load --input /tmp/starlette-transformers-gpu.tar
      - run: docker image ls